### ISSUE TITLE
Is this using a older version of sweet alert

### ISSUE THREAD

**Issue by MurWade** [kevohagan/meteor-sweetalert#6]
the sweet alert demo if you click outside the alert, 
it closes the alert and with this it does not.

Is it becuase you are using a older version of the script or it is a option in sweet alert?

**Comment by kevohagan** [comment]
Yes you are totally right! Just pushing right now and deploying to atmoshpere! Thanks for the update!

**Comment by MurWade** [comment]
thanks mate!
