### ISSUE TITLE
Unable to use "input" and "prompt" alert types

### ISSUE THREAD

**Issue by dkmooers** [kevohagan/meteor-sweetalert#7]
Anyone else unable to use "input" or "prompt" alert types with SweetAlert? All the other types seem to work for me - I've been using this plugin for a while - just not input/prompt. I've just updated to the latest 0.5.0. 

I get this error:

SweetAlert: Unknown alert type: input

Which is bizarre, since I checked the source SweetAlert js file and it has alertTypes = [... 'input', 'prompt'], so they should be working... any ideas?

**Comment by kevohagan** [comment]
hey @dkmooers could you give more details? I just tried type: 'input' and its working for me :)

**Comment by kevohagan** [comment]
did you do a git clone from github or installed from atmosphere? i had not updated the repo on github with the version published on atmosphere (0.5.0) maybe thats why

**Comment by dkmooers** [comment]
Hmm! I installed it from Atmosphere.

Here's the code I'm using (from one of the examples), inside a click event handler on one of my templates:

sweetAlert({
  title: "An input!",
  text: 'Write something interesting:',
  type: 'input',
  showCancelButton: true,
  closeOnConfirm: false,
  animation: "slide-from-top"
}, function(inputValue){
  console.log("You wrote", inputValue);   
});

When the alert fires, it shows briefly and then immediately hides again, throwing the console error mentioned in my first post. Bizarrely, when I change the type from "input" to "success", it works just fine! Are you able to reproduce this?

**Comment by dkmooers** [comment]
Whoa, strange... when I create a new meteor project and add SweetAlert and use the above "input" code, it works fine! So I tried removing SweetAlert from my current project and re-added it, and now it works fine. Must have been leftover build from previous versions or something? No idea. Anyways, thanks, got it working now!

**Comment by kevohagan** [comment]
glad it worked for you! :)
